# Generated by Django 3.1.2 on 2020-11-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articles_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendrier',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='infos',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='quisommmesnous',
            name='autor',
        ),
    ]
