# Generated by Django 3.1.2 on 2020-11-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201101_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
