# Generated by Django 3.1.2 on 2020-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='type_infos',
            field=models.CharField(choices=[('gr', 'general'), ('ra', 'randonnees'), ('ma', 'materiel')], default='gr', max_length=30),
        ),
    ]
