# Generated by Django 3.1.2 on 2020-11-08 10:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_randoscalendrier_contenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randosanimateur',
            options={'verbose_name': 'Animateurs rando', 'verbose_name_plural': 'Animateurs rando'},
        ),
        migrations.AddField(
            model_name='randosanimateur',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='randosanimateur',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
