# Generated by Django 3.1.2 on 2020-11-08 10:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201108_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='randoscommandement',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
