# Generated by Django 3.1.2 on 2020-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201108_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randoscartotheque',
            options={'verbose_name': 'Cartothèque IGN', 'verbose_name_plural': 'Cartothèque IGN'},
        ),
        migrations.AddField(
            model_name='randoscartotheque',
            name='fichier_cartotheque',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
