# Generated by Django 3.1.2 on 2020-11-08 11:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201108_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailsejour',
            options={'verbose_name': 'Séjours', 'verbose_name_plural': 'Séjours'},
        ),
        migrations.AddField(
            model_name='detailsejour',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailsejour',
            name='sejours_pdf',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsejour',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
