# Generated by Django 3.1.2 on 2020-11-08 12:05

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201108_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='photosarticles',
            options={'verbose_name': 'Galerie de photos', 'verbose_name_plural': 'Galerie de photos'},
        ),
        migrations.AddField(
            model_name='photosarticles',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photosarticles',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photosarticles',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photosarticles',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='photosarticles',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.multiimage'),
            preserve_default=False,
        ),
    ]
