# Generated by Django 3.1.2 on 2020-11-08 12:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201108_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contenu', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, upload_to='')),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Galerie de photos',
                'verbose_name_plural': 'Galerie de photos',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.photosarticle')),
            ],
        ),
        migrations.RemoveField(
            model_name='photosarticles',
            name='model',
        ),
        migrations.DeleteModel(
            name='MultiImage',
        ),
        migrations.DeleteModel(
            name='PhotosArticles',
        ),
    ]
