# Generated by Django 3.1.2 on 2020-11-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201108_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosarticle',
            name='image',
        ),
    ]
