# Generated by Django 3.1.2 on 2020-11-08 13:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_photosarticle_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhesion',
            options={'verbose_name': 'Adhésion', 'verbose_name_plural': 'Adhésion'},
        ),
        migrations.AlterModelOptions(
            name='bureau',
            options={'verbose_name': 'Bureau', 'verbose_name_plural': 'Bureau'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'Formations', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='reglementinterieur',
            options={'verbose_name': 'Règlement intérieur', 'verbose_name_plural': 'Règlement intérieur'},
        ),
        migrations.AddField(
            model_name='adhesion',
            name='adhesion_pdf',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adhesion',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bureau',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglementinterieur',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reglementinterieur',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
