# Generated by Django 3.1.2 on 2020-11-08 13:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201108_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestation',
            options={'verbose_name': 'Manifestations', 'verbose_name_plural': 'Manifestations'},
        ),
        migrations.AddField(
            model_name='manifestation',
            name='contenu',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
