# Generated by Django 3.1.2 on 2020-11-08 14:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201108_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contenu', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Accueil',
                'verbose_name_plural': 'Actualités',
            },
        ),
    ]
